version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "16:00"
  - package-ecosystem: gomod
    directory: "/devconsole"
    schedule:
      interval: daily
      time: "16:00"
  - package-ecosystem: gomod
    directory: "/reposerver"
    schedule:
      interval: daily
      time: "16:00"
    open-pull-requests-limit: 20
  - package-ecosystem: npm
    directory: "/web"
    schedule:
      interval: daily
      time: "16:00"
    open-pull-requests-limit: 20
