version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: "/devportal"
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: "/reposerver"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
  - package-ecosystem: npm
    directory: "/web"
    schedule:
      interval: daily
