version: '3'
services:
  portal:
    build: devportal
    env_file: devportal/.env
  web:
    build: web
  repo:
    build: reposerver
    env_file: reposerver/.env

  nginx:
    image: nginx:alpine
    volumes:
      - ./devportal/nginx/dev.conf:/etc/nginx/nginx.conf
      - ./devportal/nginx/security.conf:/etc/nginx/security.conf
      - ./certs:/etc/nginx/certs
    ports:
      - '8080:443'
