version: '3.8'
services:
  portal:
    build: .
    env_file: .env

  nginx:
    image: nginx:1.20-alpine
    volumes:
      - ./nginx/dev.conf:/etc/nginx/nginx.conf
      - ./nginx/security.conf:/etc/nginx/security.conf
      - ./certs:/etc/nginx/certs
      - ./web/static:/usr/share/nginx/html
    ports:
      - '8080:443'
