name: Backend

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Build devportal
        run: cd devportal && go build -v
      - name: Build reposerver
        run: cd reposerver && go build -v
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Lint devportal
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: devportal
          args: --timeout 2m
      - name: Lint reposerver
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: reposerver
          args: --timeout 2m
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Test devportal
        run: cd devportal && go test -v ./...
