name: Backend

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: Install protoc
        run: |
          sudo apt-get install protobuf-compiler
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - name: Build devconsole
        run: cd devconsole && go generate -v && go build -v
      - name: Build reposerver
        run: cd reposerver && go generate -v && go build -v
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: Install protoc
        run: |
          sudo apt-get install protobuf-compiler
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - name: Generate source
        run: cd devconsole && go generate
      - name: Lint devconsole
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: devconsole
          args: --timeout 2m
      - name: Lint reposerver
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: reposerver
          args: --timeout 2m
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: Install protoc
        run: |
          sudo apt-get install protobuf-compiler
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - name: Test devconsole
        run: cd devconsole && go generate && go test -v ./...
