name: Frontend

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: cd web && npm ci
      - name: Build frontend
        run: cd web && npm run build
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: cd web && npm ci
      - name: Lint frontend
        run: cd web && npm run lint
