name: Frontend

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: cd web && npm ci
      - name: Build frontend
        run: cd web && npm run build
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: cd web && npm ci
      - name: Lint frontend
        run: cd web && npm run lint
