name: Lint frontend

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: cd web && npm ci
      - name: Lint frontend
        run: cd web && npm run lint
